Brooms:
  
  number-of-brooms: 5
  
  broom1:
    name: Cleansweep One
    speed: 0.7
    # wood shovel
    item: 269
      
  broom2:
    name: Comet 140
    speed: 0.9
    # stone shovel
    item: 273
      
  broom3:
    name: Nimbus 2000
    speed: 1.3
    # iron shovel
    item: 256
      
  broom4:
    name: Nimbus 2001
    speed: 1.4
    # gold shovel
    item: 284
      
  broom5:
    name: Firebolt
    speed: 2.0
    # diamond shovel
    item: 277
  