name: BroomSticks
version: 3.0.0
main: com.DanMan.main.BroomSticks
commands:
  q:
    description: Manipulate quidditch stadium and game.
    usage: /q <new|delete|start|stop> "arena-name"
    permission-message: You don't have <permission>
  broom:
    description: Gives a broom to a player or yourself.
    usage: /broom [player] "broom-name"
    permission-message: You don't have <permission>
permissions:
    broomsticks.*:
        description: Gives access to all broomstick commands
        children:
            broomsticks.spawn: true
    broomSticks.spawn:
        description: Allows you to spawn in a broom with a command.
        default: op
    broomSticks.quidditch:
        description: Allows you to use all quidditch commands.
        default: op